import React from 'react'
import { render, screen, fireEvent } from '@testing-library/react'
import App from '../App'

describe('show alert', () => {
    test('case - button is clicked with an empty input', () => {
        render(<App />)
        const button = screen.getByText('submit')
        fireEvent.click(button)
        expect(screen.getByText('Oh snap! You got an error!')).toBeInTheDocument()
    })
    test(`case - input is submited without containing the "is" word`, () => {
        render(<App />)
        const input = screen.getByTestId('input-test-id')
        const button = screen.getByText('submit')
        fireEvent.click(input, { target: { value: 'one i I' } })
        fireEvent.click(button)
        expect(screen.getByText('Oh snap! You got an error!')).toBeInTheDocument()
    })
    test('case - nonsense input', () => {
        render(<App />)
        const input = screen.getByTestId('input-test-id')
        const button = screen.getByText('submit')
        fireEvent.click(input, { target: { value: 'how much wood could a woodchuck chuck if a woodchuck could chuck wood ?' } })
        fireEvent.click(button)
        expect(screen.getByText('Oh snap! You got an error!')).toBeInTheDocument()
    })
})

describe('output the correct answer', () => {
    test('case 1 - how much is pish tegj glob glob ?', () => {
        render(<App />)
        const input = screen.getByTestId('input-test-id')
        const button = screen.getByText('submit')
        fireEvent.change(input, { target: { value: 'glob is I' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'pish is X' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'tegj is L' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'how much is pish tegj glob glob ?' } })
        fireEvent.click(button)
        expect(screen.getByText('42')).toBeInTheDocument()
    })
    test('case 2 - how many Credits is glob prok Silver ?', () => {
        render(<App />)
        const input = screen.getByTestId('input-test-id')
        const button = screen.getByText('submit')
        fireEvent.change(input, { target: { value: 'glob is I' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'prok is V' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'glob glob Silver is 34 Credits' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'how many Credits is glob prok Silver ?' } })
        fireEvent.click(button)
        expect(screen.getByText('68 credits')).toBeInTheDocument()
    })
    test('case 3 - how many Credits is glob prok Gold ?', () => {
        render(<App />)
        const input = screen.getByTestId('input-test-id')
        const button = screen.getByText('submit')
        fireEvent.change(input, { target: { value: 'glob is I' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'prok is V' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'glob prok Gold is 57800 Credits' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'how many Credits is glob prok Gold ?' } })
        fireEvent.click(button)
        expect(screen.getByText('57800 credits')).toBeInTheDocument()
    })
    test('case 4 - how many Credits is glob prok Iron ?', () => {
        render(<App />)
        const input = screen.getByTestId('input-test-id')
        const button = screen.getByText('submit')
        fireEvent.change(input, { target: { value: 'glob is I' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'prok is V' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'pish is X' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'pish pish Iron is 3910 Credits' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'how many Credits is glob prok Iron ?' } })
        fireEvent.click(button)
        expect(screen.getByText('782 credits')).toBeInTheDocument()
    })
    test('case 5 - how much is moon moon xorx moon krak xorx xrox tegj glob glob ?', () => {
        render(<App />)
        const input = screen.getByTestId('input-test-id')
        const button = screen.getByText('submit')
        fireEvent.change(input, { target: { value: 'glob is I' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'pish is X' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'tegj is L' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'xorx is C' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'krak is D' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'moon is M' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'how much is moon moon xorx moon krak xorx xorx tegj glob glob ?' } })
        fireEvent.click(button)
        expect(screen.getByText('3652')).toBeInTheDocument()
    })
    test('case 6 - how many Credits is moon moon xorx moon krak xorx xorx tegj glob glob Bronze ?', () => {
        render(<App />)
        const input = screen.getByTestId('input-test-id')
        const button = screen.getByText('submit')
        fireEvent.change(input, { target: { value: 'glob is I' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'pish is X' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'tegj is L' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'xorx is C' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'krak is D' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'moon is M' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'krak xorx pish glob bronze is 111910 Credits' } })
        fireEvent.click(button)
        fireEvent.change(input, { target: { value: 'how many Credits is moon moon xorx moon krak xorx xorx tegj glob glob Bronze ?' } })
        fireEvent.click(button)
        expect(screen.getByText('668896 credits')).toBeInTheDocument()
    })
})
